using System.Data;
using Microsoft.EntityFrameworkCore;

namespace Portifolio.Web.Data;

public static class SchemaUpgrades
{
    public static async Task ApplyAsync(AppDbContext db)
    {
        var provider = db.Database.ProviderName ?? "";
        if (provider.Contains("Sqlite", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "Stacks" (
                    "Id" INTEGER NOT NULL CONSTRAINT "PK_Stacks" PRIMARY KEY AUTOINCREMENT,
                    "Name" TEXT NOT NULL,
                    "SortOrder" INTEGER NOT NULL
                );
                """);
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "ProjectStacks" (
                    "ProjectId" INTEGER NOT NULL,
                    "StackId" INTEGER NOT NULL,
                    "SortOrder" INTEGER NOT NULL,
                    CONSTRAINT "PK_ProjectStacks" PRIMARY KEY ("ProjectId", "StackId"),
                    FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
                    FOREIGN KEY ("StackId") REFERENCES "Stacks" ("Id") ON DELETE CASCADE
                );
                """);
            await db.Database.ExecuteSqlRawAsync("""
                CREATE INDEX IF NOT EXISTS "IX_ProjectStacks_StackId" ON "ProjectStacks" ("StackId");
                """);
            await EnsureSqliteColumnAsync(db, "Projects", "Links", "TEXT NOT NULL DEFAULT '[]'");
            return;
        }

        if (provider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "Stacks" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" text NOT NULL,
                    "SortOrder" integer NOT NULL
                );
                """);
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "ProjectStacks" (
                    "ProjectId" integer NOT NULL,
                    "StackId" integer NOT NULL,
                    "SortOrder" integer NOT NULL,
                    PRIMARY KEY ("ProjectId", "StackId"),
                    CONSTRAINT "FK_ProjectStacks_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_ProjectStacks_Stacks_StackId" FOREIGN KEY ("StackId") REFERENCES "Stacks" ("Id") ON DELETE CASCADE
                );
                """);
            await db.Database.ExecuteSqlRawAsync("""
                ALTER TABLE "Projects" ADD COLUMN IF NOT EXISTS "Links" text NOT NULL DEFAULT '[]';
                """);
            return;
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS `Stacks` (
                `Id` int NOT NULL AUTO_INCREMENT,
                `Name` longtext NOT NULL,
                `SortOrder` int NOT NULL,
                PRIMARY KEY (`Id`)
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS `ProjectStacks` (
                `ProjectId` int NOT NULL,
                `StackId` int NOT NULL,
                `SortOrder` int NOT NULL,
                PRIMARY KEY (`ProjectId`, `StackId`),
                CONSTRAINT `FK_ProjectStacks_Projects_ProjectId` FOREIGN KEY (`ProjectId`) REFERENCES `Projects` (`Id`) ON DELETE CASCADE,
                CONSTRAINT `FK_ProjectStacks_Stacks_StackId` FOREIGN KEY (`StackId`) REFERENCES `Stacks` (`Id`) ON DELETE CASCADE
            );
            """);
    }

    private static async Task EnsureSqliteColumnAsync(AppDbContext db, string table, string column, string definition)
    {
        var exists = false;
        var conn = db.Database.GetDbConnection();
        var opened = conn.State == ConnectionState.Open;
        if (!opened)
            await conn.OpenAsync();
        try
        {
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = $"PRAGMA table_info(\"{table}\")";
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                if (string.Equals(Convert.ToString(reader["name"]), column, StringComparison.OrdinalIgnoreCase))
                {
                    exists = true;
                    break;
                }
            }
        }
        finally
        {
            if (!opened)
                await conn.CloseAsync();
        }

        if (!exists)
            await db.Database.ExecuteSqlRawAsync($"ALTER TABLE \"{table}\" ADD COLUMN \"{column}\" {definition}");
    }
}
